### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grassjelly** [RobotLocomotion/LittleDog#5]
Hi @RussTedrake ,

Thanks for porting this from a private repo. May I know what's the license like? I'm planning to make changes on the URDF file so it can be run on ROS/Gazebo and open sourcing it.

Thank you!

**Comment by RussTedrake** [comment]
I would copy the drake license.  If you are willing to PR the copy, that would be awesome.

**Comment by grassjelly** [comment]
Thank you!
